### ISSUE TITLE
New App Icon 

### ISSUE THREAD

**Issue by fabi94music** [milgra/highsierramediakeyenabler#51]
see #49 

![hsmke](https://user-images.githubusercontent.com/29753374/43044278-8f154672-8da3-11e8-9d13-44be94ef6a37.png)

Would love to have a app icon instead of a black dot only. 
Plus an option to hide the menu bar icon would be nice. 
What do you think?

**Comment by Hum4n01d** [comment]
I don't think it makes sense to make it seem like an app where you can control your music, this is just a utility, a really useful one at that, but it isn't a music control app like your icon implies

**Comment by milgra** [comment]
Well, I agree that the dot is too simple but I wanted the thinnest menu bar icon possible. I'm thinking about something different. About the icon hiding : I cannot make it invisible because then it would be impossible to reach the menu and to quit. But there are handy macOS utilities for this purpose, check out Vanilla for example : [https://matthewpalmer.net/vanilla/](https://matthewpalmer.net/vanilla/)
